spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
#    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
#    username: ${PGUSER}
#    password: ${PGPASSWORD}
    hikari:
      auto-commit: false


security:
  cors:
    allowed-origins:
      - "*"
      - http://localhost:4200
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS

